added adding files in github with auth token
Regis-Caelum/daem pull request #8
Opened 2023-02-02 11:38 UTC by AbhayDhaundiyal

2023-02-02 11:45 UTC, AbhayDhaundiyal commented
Closes #6

2023-02-02 11:50 UTC, Regis-Caelum requested changes
Please do the changes and LMK when youre done

2023-02-02 11:50 UTC, Regis-Caelum commented on common/common.go
> +	vv, err := node.Info.Info()
Use appropriate variable name

2023-02-02 11:50 UTC, Regis-Caelum commented on common/common.go
> +	if !vv.IsDir() {
implement this logic under `CreaterefOnGitHub` function

2023-02-02 11:50 UTC, Regis-Caelum commented on common/common.go
> +func CreateRefOnGitHub(gitPath string, node *Node, gitHubUrl string) {
Don't change the function defination, just implement it

2023-02-02 11:50 UTC, Regis-Caelum commented on main.go
> +	path := "/home/kenkaneki124/dronebase"
use env variables for sensitive info

2023-02-02 11:53 UTC, Regis-Caelum commented
please provide description for the PR and use significant commit messages

2023-02-02 12:10 UTC, AbhayDhaundiyal commented on main.go
> +	path := "/home/kenkaneki124/dronebase"
Done!

2023-02-02 12:28 UTC, AbhayDhaundiyal commented
I have resolved the issue please review it @Regis-Caelum

2023-02-03 05:32 UTC, Regis-Caelum approved these changes
Nice,
Keep up the good work :+1:

2023-02-03 05:34 UTC, merged